# Generated by Django 3.0.2 on 2020-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_movies', '0002_auto_20200611_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
