# Generated by Django 3.0.2 on 2020-06-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_movies', '0003_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
