query AllMovies {
  movies {
    rank
    title
    synopsis
    duration
    director
  }
}

# query AllMoviesFromClient {
#   movies @client {
#     rank
#     title
#     synopsis
#     duration
#     director
#   }
# }
